name: kireimics
description: "KIREIMICS"

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  marquee: ^2.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  go_router: ^14.8.1
  url_strategy: ^0.3.0
  http: ^1.3.0
  get: ^4.7.2
  html: ^0.15.5
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  animations: ^2.0.11
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  razorpay_flutter: ^1.4.0
  js: ^0.7.2
  encrypt: ^5.0.3
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/header/
    - assets/sidebar/
    - assets/home_page/
    - assets/above_footer/
    - assets/grouped_alphabet/
    - assets/loader/
    - assets/footer/
    - assets/chat_bot/
    - assets/drawer/
    - assets/about_us/
    - assets/icons/

  fonts:
    - family: Cralika
      fonts:
        - asset: fonts/Cralika.ttf

